\omit \title Mobile HTML5 Guide for WebKit \endomit

- \l{Introduction}

- __Deploying Web Apps__

	\li \l{Web Apps}
	\li \l{Responsive Interfaces}
\omit	\li \l{Performance Testing}                     \endomit

- __Layout and Formatting__

	\li \l{Flexible Mobile Layout}
	\li \l{Tipping the Handset}
	\li \l{Colors and Backgrounds}
	\li \l{Borders and Overflows}
	\li \l{Typography}

- __Dynamic Graphics__

	\li \l{Animations}
	\li \l{Transforms}
	\li \l{Multimedia}
	\li \l{Canvas}
\omit	\li \l{WebGL}                                   \endomit
\omit	\li \l{[SVG]} \endomit

- __Input and Interaction__

	\li \l{Touch Gestures}
\omit	\li \l{Drag & Drop}                             \endomit
	\li \l{Input Types}
	\li \l{Input Validation}
	\li \l{Editable Text}
	\li \l{Session History}
	\li \l{Location and Travel}
	\li \l{Orientation and Motion}
\omit	\li \l{Speech Input}                            \endomit

\omit

	\li \l{Data Capture}
	\li \l{User data}
	\li \l{Other Sensors}
	\li \l{Detecting proximity and making payments}
	\li \l{Sending Notifications}

\endomit

- __Storage and Communication__

	\li \l{Offline Mode}
	\li \l{Data Storage}
	\li \l{Accessing the File System}
	\li \l{Messages and Workers}
\omit	\li \l{Ajax 2} \endomit
	\li \l{Web Sockets}
\omit	\li \l{Microdata}                               \endomit

- \l{Core APIs}

